title: CSE 198 WI26
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Deployment Settings
url: "https://www.andrewcjeter.com"
baseurl: "/cse198-wi26"

# Navigation
aux_links:
  "HKN Outreach Portal": https://portal.hknucsd.com/
  "Discord": https://discord.gg/8MJyMj6HKr

# Search
search_enabled: true
heading_anchors: true

# Footer
footer_content: "CSE 198 Winter 2026 - Copyright Â© 2026 [Andrew Jeter](https://www.andrewcjeter.com) - University of California, San Diego"

# Collections (optional, enables _assignments folder if we want strict collection usage)
collections:
  assignments:
    output: true
    permalink: /assignments/:path/
  guides:
    output: true
    permalink: /guides/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets"
    values:
      layout: null

# Callouts
color_scheme: light
remote_theme: just-the-docs/just-the-docs@v0.5.4

callouts_level: loud  # loud = shaded box, quiet = subtle
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: red
  warning:
    title: Warning
    color: purple
  note:
    title: Note
    color: blue
  new:
    title: New
    color: green
