title: CSE 198 Winter 2026
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Navigation
aux_links:
  "HKN Outreach Portal": https://hknhub.ucsd.edu/
  "Discord": https://discord.gg/8MJyMj6HKr

# Search
search_enabled: true
heading_anchors: true

# Footer
footer_content: "CSE 198 Winter 2026 | UC San Diego"

# Collections (optional, enables _assignments folder if we want strict collection usage)
collections:
  assignments:
    output: true
    permalink: /assignments/:path/
  guides:
    output: true
    permalink: /guides/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
